// <auto-generated />
using System;
using Assessment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Assessment.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Assessment.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AnswerSectionId");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedId");

                    b.Property<int>("ExamEmployeeId");

                    b.Property<int>("ExamSectionId");

                    b.Property<string>("Item");

                    b.Property<int>("QuestionId");

                    b.HasKey("Id");

                    b.HasIndex("AnswerSectionId");

                    b.HasIndex("CreatedId");

                    b.HasIndex("ExamEmployeeId");

                    b.HasIndex("ExamSectionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            ExamEmployeeId = 1,
                            ExamSectionId = 1,
                            Item = "1, 3, 2, 6, 5, 15, 14, ....",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            ExamEmployeeId = 1,
                            ExamSectionId = 1,
                            Item = "100, 95, ..., 91, 92, 87, 88, 83.",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            ExamEmployeeId = 1,
                            ExamSectionId = 2,
                            Item = "INSOMNIA = ...",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            ExamEmployeeId = 1,
                            ExamSectionId = 2,
                            Item = "BONGSOR >< ...",
                            QuestionId = 4
                        });
                });

            modelBuilder.Entity("Assessment.Models.AnswerDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AnswerId");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedId");

                    b.Property<bool?>("IsTrue");

                    b.Property<string>("Item");

                    b.Property<int?>("QuestionDetailId");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("CreatedId");

                    b.HasIndex("QuestionDetailId");

                    b.ToTable("AnswerDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnswerId = 1,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            IsTrue = true,
                            Item = "42",
                            QuestionDetailId = 4
                        },
                        new
                        {
                            Id = 2,
                            AnswerId = 2,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            IsTrue = true,
                            Item = "96",
                            QuestionDetailId = 9
                        },
                        new
                        {
                            Id = 3,
                            AnswerId = 3,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            IsTrue = true,
                            Item = "Tidak bisa tidur",
                            QuestionDetailId = 13
                        },
                        new
                        {
                            Id = 4,
                            AnswerId = 4,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            IsTrue = true,
                            Item = "Kerdil",
                            QuestionDetailId = 16
                        });
                });

            modelBuilder.Entity("Assessment.Models.AnswerQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AnswerSectionId");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("CreatedId");

                    b.Property<TimeSpan>("Duration");

                    b.Property<int>("Number");

                    b.Property<int>("QuestionId");

                    b.HasKey("Id");

                    b.HasIndex("AnswerSectionId");

                    b.HasIndex("CreatedId");

                    b.HasIndex("QuestionId");

                    b.ToTable("AnswerQuestion");
                });

            modelBuilder.Entity("Assessment.Models.AnswerSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedId");

                    b.Property<TimeSpan>("Duration");

                    b.Property<int>("ExamEmployeeId");

                    b.Property<int>("ExamId");

                    b.Property<string>("Name");

                    b.Property<string>("Notes");

                    b.Property<int>("SectionId");

                    b.HasKey("Id");

                    b.HasIndex("CreatedId");

                    b.HasIndex("ExamEmployeeId");

                    b.HasIndex("ExamId");

                    b.HasIndex("SectionId");

                    b.ToTable("AnswerSections");
                });

            modelBuilder.Entity("Assessment.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "233e5870-bfa6-4ba4-b3bd-73cf85c5d173",
                            Email = "admin@rekrutmen.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@REKRUTMEN.COM",
                            NormalizedUserName = "ADMIN@REKRUTMEN.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEEp1sap4dxD2mtlMuEPd5CIN2p1lcaKGjOejHk2GjLl+BwkmCW38AtHU5fhBkmlOOA==",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "7a1e8e47-50f4-4922-a855-7001a615fb5e",
                            TwoFactorEnabled = false,
                            UserName = "admin@rekrutmen.com"
                        },
                        new
                        {
                            Id = "77e285fb-43e8-4846-b763-9fcc0138ea99",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "93182e87-c18a-4fc7-8ac7-63100c9e803e",
                            Email = "adindanamira97@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADINDANAMIRA97@GMAIL.COM",
                            NormalizedUserName = "ADINDANAMIRA97@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEMiQscjx4+VAFyt6lKUPW2AkZ6mLOtJcnTST6KOYclS3VFLwMFKdD61UA2S9iVlYig==",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "80b9327b-15db-49c9-86fa-1e3f21b74bb7",
                            TwoFactorEnabled = false,
                            UserName = "adindanamira97@gmail.com"
                        },
                        new
                        {
                            Id = "02840db7-b582-454f-a83b-802b68cd33f0",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "216c4a56-0c6d-4908-87d4-7388153f4926",
                            Email = "testing@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "TESTING@GMAIL.COM",
                            NormalizedUserName = "TESTING@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEMiQscjx4+VAFyt6lKUPW2AkZ6mLOtJcnTST6KOYclS3VFLwMFKdD61UA2S9iVlYig==",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "8067b3a3-a100-43a5-ae6a-0e294f817f9e",
                            TwoFactorEnabled = false,
                            UserName = "testing@gmail.com"
                        });
                });

            modelBuilder.Entity("Assessment.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CreatedId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "SUB",
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            Name = "Surabaya"
                        },
                        new
                        {
                            Id = 2,
                            Code = "CGK",
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            Name = "Jakarta"
                        });
                });

            modelBuilder.Entity("Assessment.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("BirthDatePlace")
                        .IsRequired();

                    b.Property<int>("CityId");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedId");

                    b.Property<int>("GenderId");

                    b.Property<long>("IdentityNumber");

                    b.Property<int>("MaritalStatusId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("ReligionId");

                    b.Property<string>("UserForeignKey")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CreatedId");

                    b.HasIndex("GenderId");

                    b.HasIndex("MaritalStatusId");

                    b.HasIndex("ReligionId");

                    b.HasIndex("UserForeignKey")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Jl Surabaya No 1",
                            BirthDate = new DateTime(1990, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthDatePlace = "Surabaya",
                            CityId = 1,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            GenderId = 2,
                            IdentityNumber = 1234567890L,
                            MaritalStatusId = 1,
                            Name = "Adinda Namira",
                            ReligionId = 1,
                            UserForeignKey = "77e285fb-43e8-4846-b763-9fcc0138ea99"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Jl Surabaya No 1",
                            BirthDate = new DateTime(1991, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BirthDatePlace = "Surabaya",
                            CityId = 1,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            GenderId = 2,
                            IdentityNumber = 9999999999L,
                            MaritalStatusId = 1,
                            Name = "Testing Dua",
                            ReligionId = 1,
                            UserForeignKey = "02840db7-b582-454f-a83b-802b68cd33f0"
                        });
                });

            modelBuilder.Entity("Assessment.Models.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedId");

                    b.Property<TimeSpan>("Duration");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedId");

                    b.ToTable("Exams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            Duration = new TimeSpan(0, 0, 0, 0, 0),
                            Name = "Rekrutmen Grade 6A"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            Duration = new TimeSpan(0, 0, 0, 0, 0),
                            Name = "Rekrutmen Grade 7A"
                        });
                });

            modelBuilder.Entity("Assessment.Models.ExamEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedId");

                    b.Property<int>("EmployeeId");

                    b.Property<int>("ExamScheduleId");

                    b.HasKey("Id");

                    b.HasIndex("CreatedId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ExamScheduleId");

                    b.ToTable("ExamEmployees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            EmployeeId = 1,
                            ExamScheduleId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            EmployeeId = 2,
                            ExamScheduleId = 1
                        });
                });

            modelBuilder.Entity("Assessment.Models.ExamQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedId");

                    b.Property<TimeSpan>("Duration");

                    b.Property<int>("ExamSectionId");

                    b.Property<int>("Number");

                    b.Property<int>("QuestionId");

                    b.HasKey("Id");

                    b.HasIndex("CreatedId");

                    b.HasIndex("ExamSectionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("ExamQuestions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            Duration = new TimeSpan(0, 0, 0, 0, 0),
                            ExamSectionId = 1,
                            Number = 0,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            Duration = new TimeSpan(0, 0, 0, 0, 0),
                            ExamSectionId = 1,
                            Number = 0,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            Duration = new TimeSpan(0, 0, 0, 0, 0),
                            ExamSectionId = 2,
                            Number = 0,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            Duration = new TimeSpan(0, 0, 0, 0, 0),
                            ExamSectionId = 2,
                            Number = 0,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            Duration = new TimeSpan(0, 0, 0, 0, 0),
                            ExamSectionId = 3,
                            Number = 0,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            Duration = new TimeSpan(0, 0, 0, 0, 0),
                            ExamSectionId = 3,
                            Number = 0,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            Duration = new TimeSpan(0, 0, 0, 0, 0),
                            ExamSectionId = 4,
                            Number = 0,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            Duration = new TimeSpan(0, 0, 0, 0, 0),
                            ExamSectionId = 4,
                            Number = 0,
                            QuestionId = 4
                        });
                });

            modelBuilder.Entity("Assessment.Models.ExamSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedId");

                    b.Property<DateTime>("DateExam");

                    b.Property<TimeSpan>("Duration");

                    b.Property<int>("ExamId");

                    b.Property<string>("Notes");

                    b.HasKey("Id");

                    b.HasIndex("CreatedId");

                    b.HasIndex("ExamId");

                    b.ToTable("ExamSchedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            DateExam = new DateTime(2019, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = new TimeSpan(0, 0, 0, 0, 0),
                            ExamId = 1,
                            Notes = ""
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            DateExam = new DateTime(2019, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = new TimeSpan(0, 0, 0, 0, 0),
                            ExamId = 2,
                            Notes = ""
                        });
                });

            modelBuilder.Entity("Assessment.Models.ExamSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedId");

                    b.Property<TimeSpan>("Duration");

                    b.Property<int>("ExamId");

                    b.Property<string>("Name");

                    b.Property<string>("Notes");

                    b.Property<int>("SectionId");

                    b.HasKey("Id");

                    b.HasIndex("CreatedId");

                    b.HasIndex("ExamId");

                    b.HasIndex("SectionId");

                    b.ToTable("ExamSections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            Duration = new TimeSpan(0, 0, 0, 0, 0),
                            ExamId = 1,
                            Name = "Tes Potensi Akademik 6A",
                            SectionId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            Duration = new TimeSpan(0, 0, 0, 0, 0),
                            ExamId = 1,
                            Name = "Tes Psikotes 6A",
                            SectionId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            Duration = new TimeSpan(0, 0, 0, 0, 0),
                            ExamId = 2,
                            Name = "Tes Potensi Akademik 7A",
                            SectionId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            Duration = new TimeSpan(0, 0, 0, 0, 0),
                            ExamId = 2,
                            Name = "Tes Psikotes 7A",
                            SectionId = 2
                        });
                });

            modelBuilder.Entity("Assessment.Models.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CreatedId");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "L",
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            Name = "Laki-laki"
                        },
                        new
                        {
                            Id = 2,
                            Code = "P",
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            Name = "Perempuan"
                        });
                });

            modelBuilder.Entity("Assessment.Models.MaritalStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CreatedId");

                    b.ToTable("MaritalStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "BK",
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            Name = "Belum Kawin"
                        },
                        new
                        {
                            Id = 2,
                            Code = "K",
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            Name = "Kawin"
                        });
                });

            modelBuilder.Entity("Assessment.Models.Navigation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Action");

                    b.Property<string>("Area");

                    b.Property<string>("Controller");

                    b.Property<bool>("IsActive");

                    b.Property<int?>("NextOrderId");

                    b.Property<int>("OrderId");

                    b.Property<string>("Path");

                    b.Property<int?>("PrevOrderId");

                    b.Property<string>("Route");

                    b.HasKey("Id");

                    b.ToTable("Navigations");
                });

            modelBuilder.Entity("Assessment.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedId");

                    b.Property<TimeSpan>("Duration");

                    b.Property<string>("Item");

                    b.Property<int>("QuestionTypeId");

                    b.HasKey("Id");

                    b.HasIndex("CreatedId");

                    b.HasIndex("QuestionTypeId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            Duration = new TimeSpan(0, 0, 0, 0, 0),
                            Item = "1, 3, 2, 6, 5, 15, 14, ....",
                            QuestionTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            Duration = new TimeSpan(0, 0, 0, 0, 0),
                            Item = "100, 95, ..., 91, 92, 87, 88, 83.",
                            QuestionTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            Duration = new TimeSpan(0, 0, 0, 0, 0),
                            Item = "INSOMNIA = ...",
                            QuestionTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            Duration = new TimeSpan(0, 0, 0, 0, 0),
                            Item = "BONGSOR >< ...",
                            QuestionTypeId = 1
                        });
                });

            modelBuilder.Entity("Assessment.Models.QuestionDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedId");

                    b.Property<bool?>("IsTrue");

                    b.Property<string>("Item");

                    b.Property<int>("QuestionId");

                    b.HasKey("Id");

                    b.HasIndex("CreatedId");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            IsTrue = false,
                            Item = "24",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            IsTrue = false,
                            Item = "28",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            IsTrue = false,
                            Item = "32",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            IsTrue = true,
                            Item = "42",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            IsTrue = false,
                            Item = "52",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            IsTrue = false,
                            Item = "90",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            IsTrue = false,
                            Item = "92",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            IsTrue = false,
                            Item = "94",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            IsTrue = true,
                            Item = "96",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            IsTrue = false,
                            Item = "97",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            IsTrue = false,
                            Item = "Cemas",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            IsTrue = false,
                            Item = "Sedih",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            IsTrue = true,
                            Item = "Tidak bisa tidur",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            IsTrue = false,
                            Item = "Kenyataanya",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            IsTrue = false,
                            Item = "Menumpuk",
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            IsTrue = true,
                            Item = "Kerdil",
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            IsTrue = false,
                            Item = "Macet",
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            IsTrue = false,
                            Item = "Susut",
                            QuestionId = 4
                        });
                });

            modelBuilder.Entity("Assessment.Models.QuestionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedId");

                    b.ToTable("QuestionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            Name = "Multiple Choice"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            Name = "Multiple Answer"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            Name = "Essay"
                        });
                });

            modelBuilder.Entity("Assessment.Models.Religion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CreatedId");

                    b.ToTable("Religions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ISL",
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            Name = "Islam"
                        },
                        new
                        {
                            Id = 2,
                            Code = "KTP",
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            Name = "Kristen Protestan"
                        },
                        new
                        {
                            Id = 3,
                            Code = "KTK",
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            Name = "Kristen Katolik"
                        },
                        new
                        {
                            Id = 4,
                            Code = "HIN",
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            Name = "Hindu"
                        },
                        new
                        {
                            Id = 5,
                            Code = "BUD",
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            Name = "Buddha"
                        },
                        new
                        {
                            Id = 6,
                            Code = "KHO",
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            Name = "Khonghucu"
                        });
                });

            modelBuilder.Entity("Assessment.Models.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedId");

                    b.Property<TimeSpan>("Duration");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedId");

                    b.ToTable("Sections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            Duration = new TimeSpan(0, 0, 0, 0, 0),
                            Name = "Tes Potensi Akademik"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2019, 10, 14, 18, 2, 41, 714, DateTimeKind.Local),
                            CreatedId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            Duration = new TimeSpan(0, 0, 0, 0, 0),
                            Name = "Tes Psikotes"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "32ff273e-e327-4f0b-b08e-a2e02b0880d6",
                            ConcurrencyStamp = "c6c609bd-85da-4629-9c56-f23c489830d2",
                            Name = "Admin",
                            NormalizedName = "Admin"
                        },
                        new
                        {
                            Id = "04e83eaf-298f-4be6-9f05-2956b2030e5e",
                            ConcurrencyStamp = "5402d890-3359-4b8f-a144-9d2afee67e1d",
                            Name = "Peserta",
                            NormalizedName = "Peserta"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "f91a6f48-4c5b-4750-8341-bbb4d6905c74",
                            RoleId = "32ff273e-e327-4f0b-b08e-a2e02b0880d6"
                        },
                        new
                        {
                            UserId = "77e285fb-43e8-4846-b763-9fcc0138ea99",
                            RoleId = "04e83eaf-298f-4be6-9f05-2956b2030e5e"
                        },
                        new
                        {
                            UserId = "02840db7-b582-454f-a83b-802b68cd33f0",
                            RoleId = "04e83eaf-298f-4be6-9f05-2956b2030e5e"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Assessment.Models.Answer", b =>
                {
                    b.HasOne("Assessment.Models.AnswerSection")
                        .WithMany("Answers")
                        .HasForeignKey("AnswerSectionId");

                    b.HasOne("Assessment.Models.ApplicationUser", "Created")
                        .WithMany("Answers")
                        .HasForeignKey("CreatedId");

                    b.HasOne("Assessment.Models.ExamEmployee", "ExamEmployee")
                        .WithMany("Answers")
                        .HasForeignKey("ExamEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Assessment.Models.ExamSection", "ExamSection")
                        .WithMany("Answers")
                        .HasForeignKey("ExamSectionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Assessment.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Assessment.Models.AnswerDetail", b =>
                {
                    b.HasOne("Assessment.Models.Answer", "Answer")
                        .WithMany("AnswerDetails")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Assessment.Models.ApplicationUser", "Created")
                        .WithMany("AnswerDetails")
                        .HasForeignKey("CreatedId");

                    b.HasOne("Assessment.Models.QuestionDetail", "QuestionDetail")
                        .WithMany("AnswerDetails")
                        .HasForeignKey("QuestionDetailId");
                });

            modelBuilder.Entity("Assessment.Models.AnswerQuestion", b =>
                {
                    b.HasOne("Assessment.Models.AnswerSection", "AnswerSection")
                        .WithMany("AnswerQuestions")
                        .HasForeignKey("AnswerSectionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Assessment.Models.ApplicationUser", "Created")
                        .WithMany()
                        .HasForeignKey("CreatedId");

                    b.HasOne("Assessment.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Assessment.Models.AnswerSection", b =>
                {
                    b.HasOne("Assessment.Models.ApplicationUser", "Created")
                        .WithMany()
                        .HasForeignKey("CreatedId");

                    b.HasOne("Assessment.Models.ExamEmployee", "ExamEmployee")
                        .WithMany()
                        .HasForeignKey("ExamEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Assessment.Models.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Assessment.Models.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Assessment.Models.City", b =>
                {
                    b.HasOne("Assessment.Models.ApplicationUser", "Created")
                        .WithMany("Cities")
                        .HasForeignKey("CreatedId");
                });

            modelBuilder.Entity("Assessment.Models.Employee", b =>
                {
                    b.HasOne("Assessment.Models.City", "City")
                        .WithMany("Employees")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Assessment.Models.ApplicationUser", "Created")
                        .WithMany("Employees")
                        .HasForeignKey("CreatedId");

                    b.HasOne("Assessment.Models.Gender", "Gender")
                        .WithMany("Employees")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Assessment.Models.MaritalStatus", "MaritalStatus")
                        .WithMany("Employees")
                        .HasForeignKey("MaritalStatusId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Assessment.Models.Religion", "Religion")
                        .WithMany("Employees")
                        .HasForeignKey("ReligionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Assessment.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("Employee")
                        .HasForeignKey("Assessment.Models.Employee", "UserForeignKey")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Assessment.Models.Exam", b =>
                {
                    b.HasOne("Assessment.Models.ApplicationUser", "Created")
                        .WithMany("Exams")
                        .HasForeignKey("CreatedId");
                });

            modelBuilder.Entity("Assessment.Models.ExamEmployee", b =>
                {
                    b.HasOne("Assessment.Models.ApplicationUser", "Created")
                        .WithMany("ExamEmployees")
                        .HasForeignKey("CreatedId");

                    b.HasOne("Assessment.Models.Employee", "Employee")
                        .WithMany("ExamEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Assessment.Models.ExamSchedule", "ExamSchedule")
                        .WithMany("ExamEmployees")
                        .HasForeignKey("ExamScheduleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Assessment.Models.ExamQuestion", b =>
                {
                    b.HasOne("Assessment.Models.ApplicationUser", "Created")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("CreatedId");

                    b.HasOne("Assessment.Models.ExamSection", "ExamSection")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("ExamSectionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Assessment.Models.Question", "Question")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Assessment.Models.ExamSchedule", b =>
                {
                    b.HasOne("Assessment.Models.ApplicationUser", "Created")
                        .WithMany("ExamSchedules")
                        .HasForeignKey("CreatedId");

                    b.HasOne("Assessment.Models.Exam", "Exam")
                        .WithMany("ExamSchedules")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Assessment.Models.ExamSection", b =>
                {
                    b.HasOne("Assessment.Models.ApplicationUser", "Created")
                        .WithMany("ExamSections")
                        .HasForeignKey("CreatedId");

                    b.HasOne("Assessment.Models.Exam", "Exam")
                        .WithMany("ExamSections")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Assessment.Models.Section", "Section")
                        .WithMany("ExamSections")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Assessment.Models.Gender", b =>
                {
                    b.HasOne("Assessment.Models.ApplicationUser", "Created")
                        .WithMany("Genders")
                        .HasForeignKey("CreatedId");
                });

            modelBuilder.Entity("Assessment.Models.MaritalStatus", b =>
                {
                    b.HasOne("Assessment.Models.ApplicationUser", "Created")
                        .WithMany("MaritalStatuses")
                        .HasForeignKey("CreatedId");
                });

            modelBuilder.Entity("Assessment.Models.Question", b =>
                {
                    b.HasOne("Assessment.Models.ApplicationUser", "Created")
                        .WithMany("Questions")
                        .HasForeignKey("CreatedId");

                    b.HasOne("Assessment.Models.QuestionType", "QuestionType")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Assessment.Models.QuestionDetail", b =>
                {
                    b.HasOne("Assessment.Models.ApplicationUser", "Created")
                        .WithMany("QuestionDetails")
                        .HasForeignKey("CreatedId");

                    b.HasOne("Assessment.Models.Question", "Question")
                        .WithMany("QuestionDetails")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Assessment.Models.QuestionType", b =>
                {
                    b.HasOne("Assessment.Models.ApplicationUser", "Created")
                        .WithMany("QuestionTypes")
                        .HasForeignKey("CreatedId");
                });

            modelBuilder.Entity("Assessment.Models.Religion", b =>
                {
                    b.HasOne("Assessment.Models.ApplicationUser", "Created")
                        .WithMany("Religions")
                        .HasForeignKey("CreatedId");
                });

            modelBuilder.Entity("Assessment.Models.Section", b =>
                {
                    b.HasOne("Assessment.Models.ApplicationUser", "Created")
                        .WithMany("Sections")
                        .HasForeignKey("CreatedId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Assessment.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Assessment.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Assessment.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Assessment.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
